### ISSUE TITLE
Can't find Node?

### ISSUE THREAD

**Issue by bipvanwinkle** [lmserrano/resume-builder#1]
I am using Node version 8.0.0. When I install resume-builder I get the following error:

`env: node\r: No such file or directory`

Any ideas where this might be coming from? I'd be happy to help fix it if you can't point me in the right direction. Thanks again for building this tool.

**Comment by bipvanwinkle** [comment]
If I delete the first line in `index.js` - `#!/usr/bin/env node` and run `node <location-of-resume-builder>` then everything works as expected.

**Comment by lmserrano** [comment]
The line endings were causing a problem after the shebang. I uniformized it to Unix-style ones (LF) and updated the github repository. Also published new version v0.1.4 with this fix in the npm repository.

Thank you for your feedback!
